site_name: SUPCIE
theme:
  name: material

  palette:

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue
    toggle:
      icon: material/weather-night
      name: Modo noturno

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: light blue
    toggle:
      icon: material/weather-sunny
      name: Modo diurno

